version: '3.8'


x-restart-policy: &restart_policy
  restart: always
  networks:
    - lab_dozzle_network
  # environment:
  #   TZ: "Asia/Ho_Chi_Minh"


networks:
  lab_dozzle_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${BRIDGE_SUBNET:-192.168.181.0/24}

services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./auth_user.yml:/data/users.yml
    ports:
      - 7007:7007

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - ./auth_user.yml:/data/users.yml
    environment:
      - DOZZLE_AUTH_TTL=48h
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_REMOTE_AGENT=${DOZZLE_AGENTS:-agent_01:7007,agent_02:7007}
    ports:
      - 8080:8080 # Dozzle UI port
