# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
version: '3.8'


x-restart-policy: &restart_policy
  restart: always
  networks:
    - lab_minio_network
  # environment:
  #   TZ: "Asia/Ho_Chi_Minh"


networks:
  lab_minio_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${BRIDGE_SUBNET:-192.168.166.0/24}

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - './data/:/data'
    command: server /data --console-address ":9090"

