version: '3.8'

x-restart-policy: &restart_policy
  restart: always
  networks:
    - lab_dbs_network
  # env_file: './.env'
  # environment:
  #   TZ: "Asia/Ho_Chi_Minh"


services:

  postgres:
    <<: *restart_policy
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    <<: *restart_policy
    image: redis
    container_name: redis
    command: redis-server --requirepass password --save 60 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
  
  mongo:
    <<: *restart_policy
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"


networks:
  lab_dbs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
